import "./globals.css";
import Nav from "../components/Nav";

export const metadata = {
  title: "mrtnbrjs.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>

      <body>
        <Nav />
        {children}
        <div style={
            {
              position:"relative",
            }
          }>
        <ul className="containerA" style={
          {
            opacity:0.5,
            zIndex:-1,
          }
        }>

            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
        </ul>
        </div>
        <div style={
            {
              position:"relative",
            }
          }>
        <ul className="containerB" style={
          {
            opacity:0.5,
            zIndex:-1,
          }
        }>

            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
        </ul>
        </div>
        <div style={
            {
              position:"relative",
            }
          }>
        <ul className="containerC" style={
          {
            opacity:0.4,
            zIndex:-1,
          }
        }>

            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
        </ul>
        </div>
        <div style={
            {
              position:"relative",
            }
          }>
        <ul className="containerD" style={
          {
            opacity:0.3,
            zIndex:-1,
          }
        }>

            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
            <li className="circle"></li>
        </ul>
        </div>
      </body>
    </html>
  );
}
