import "./globals.css";
import Nav from "../components/Nav";

export const metadata = {
  title: "mrtnbrjs.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>

      <body className="pb-40">
        <Nav />
        {children}
      </body>
    </html>
  );
}
